# Generated by Django 4.0.4 on 2022-04-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0002_house_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='modified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
