# Generated by Django 4.0.4 on 2022-04-28 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_alter_house_modified_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(blank=True, default='', editable=False, max_length=250),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
    ]
