# Generated by Django 4.0.4 on 2022-04-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0004_alter_house_address_alter_house_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='address_line_2',
            field=models.CharField(blank=True, default='', editable=False, max_length=200),
        ),
    ]
