# Generated by Django 4.0.4 on 2022-04-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0006_alter_house_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='annual_cash_flow',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Annual cash flow'),
        ),
        migrations.AlterField(
            model_name='house',
            name='closing_costs',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Closing costs'),
        ),
        migrations.AlterField(
            model_name='house',
            name='insurance',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Homeowners insurance'),
        ),
        migrations.AlterField(
            model_name='house',
            name='listing_fee',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Listing fee'),
        ),
        migrations.AlterField(
            model_name='house',
            name='llc_admin_fee_upfront',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Upfront LLC fees'),
        ),
        migrations.AlterField(
            model_name='house',
            name='llc_admin_fee_yearly',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Annual LLC administration and filing fees'),
        ),
        migrations.AlterField(
            model_name='house',
            name='maintenance_reserve',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Initial maintenance reserve'),
        ),
        migrations.AlterField(
            model_name='house',
            name='management_fees',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Property Management'),
        ),
        migrations.AlterField(
            model_name='house',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Underlying asset price'),
        ),
        migrations.AlterField(
            model_name='house',
            name='taxes',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Property Taxes'),
        ),
        migrations.AlterField(
            model_name='house',
            name='token_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='house',
            name='vacancy_reserve',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Vacancy Reserve'),
        ),
    ]
